### ISSUE TITLE
Not compiling on 10.3.1.0-12509

### ISSUE THREAD

**Issue by brmdias** [SkylineCommunications/SLC-GQIDS-CSV#1]
After cloning this repo and trying to publish it on a DMA running 10.3.1.0-12509, it fails.
Some references were moved to NuGet packages to clear some errors but there are still 7 errors in DataMiner:

![image](https://user-images.githubusercontent.com/100204121/225938302-0ada7521-c0c1-40fd-b39f-2a650690d9f7.png)

**Comment by skyline-rge** [comment]
Hi Bruno, can you show me the full error messages you get?
And how you configured your references and NuGet packages?

**Comment by brmdias** [comment]
I found the full error message in SLAutomation:
2023/03/20 19:03:16.125|SLAutomation.exe 10.2.2241.34|3760|22276|CScriptLoader::LoadScriptFromXML|INF|-1|Loaded info for script SLC-AS-CSVDataSource
2023/03/20 19:03:16.234|SLAutomation.exe 10.2.2241.34|3760|22276|CCompilationManager::CompileToLibrary|DBG|-1|Library compilation failed (0x80004005h): (70,10): error CS8137: Cannot define a class or member that utilizes tuples because the compiler required type 'System.Runtime.CompilerServices.TupleElementNamesAttribute' cannot be found. Are you missing a reference?
(70,10): error CS8356: Predefined type 'System.ValueTuple`2' is declared in multiple referenced assemblies: 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'System.ValueTuple, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
(124,10): error CS8137: Cannot define a class or member that utilizes tuples because the compiler required type 'System.Runtime.CompilerServices.TupleElementNamesAttribute' cannot be found. Are you missing a reference?
(124,10): error CS8356: Predefined type 'System.ValueTuple`2' is declared in multiple referenced assemblies: 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'System.ValueTuple, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
(85,11): error CS8356: Predefined type 'System.ValueTuple`2' is declared in multiple referenced assemblies: 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'System.ValueTuple, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
(128,11): error CS8356: Predefined type 'System.ValueTuple`2' is declared in multiple referenced assemblies: 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'System.ValueTuple, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
(132,10): error CS8356: Predefined type 'System.ValueTuple`2' is declared in multiple referenced assemblies: 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'System.ValueTuple, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

**Comment by brmdias** [comment]
removing System.ValueTuple from the DLL references fixes this:
![image](https://user-images.githubusercontent.com/100204121/226981729-77366a42-d181-4db4-8643-30b5ebf14e3d.png)
